# A pipeline with no CI trigger
trigger: none

pr: none

schedules:
- cron: "0 0,6,12,18 * * *" # Every 6Hrs https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers
  displayName: Cosmos Cron
  branches:
    include: 
    - master
  always: true # Run always irrespective of changes


variables:
  TestArguments: ' --filter "TestCategory!=Quarantine" --verbosity normal ' 
  WinVmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops 
  LinuxVmImage: ubuntu-16.04
  MacVmImage: macOS-10.14
  BuildConfiguration: Release 


jobs:
  - template:  templates/static-tools.yml
    parameters:
      BuildConfiguration: Release
      WinVmImage: $(WinVmImage)

  - template:  templates/build-test.yml
    parameters:
      BuildConfiguration: Release
      Arguments: $(TestArguments) 
      WinVmImage: $(WinVmImage)

  - template:  templates/build-test.yml
    parameters:
      BuildConfiguration: Release
      Arguments: $(TestArguments) 
      WinVmImage: $(LinuxVmImage)

  - template:  templates/build-test.yml
    parameters:
      BuildConfiguration: Release
      Arguments: $(TestArguments) 
      WinVmImage: $(MacVmImage)

  - template:  templates/build-test.yml
    parameters:
      BuildConfiguration: Debug
      Arguments: $(TestArguments) 
      WinVmImage: $(WinVmImage)
